projects:
  voterocket:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: tv3nspbcljdezebyvnpgrsepji
      endpoints:
        prod: >-
          https://6dhjj6wjynge7mwkv4livkmxqi.appsync-api.us-west-2.amazonaws.com/graphql
